insert into customers (customer_id, customer_name, email, city, signup_date) values (1, null, 'kadamiak0@hatena.ne.jp', 'Dębno', '2022-07-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (2, 'Travus Oldknow', 'toldknow1@theglobeandmail.com', 'La Palma', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (3, 'Abby Roundtree', 'aroundtree2@mediafire.com', 'Laborde', '2022-11-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (4, 'Nancee Schenfisch', 'nschenfisch3@prnewswire.com', 'Girijaya', '2023-01-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (5, 'Andros Oxenbury', null, 'Épernay', '2023-01-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (6, 'Alphard Likly', 'alikly5@privacy.gov.au', 'Chaiwan', '2022-12-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (7, 'Erastus Perschke', 'eperschke6@foxnews.com', 'Pilang', '2022-11-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (8, 'Harper Drohun', 'hdrohun7@parallels.com', null, '2022-09-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (9, 'Vassily Strattan', 'vstrattan8@slideshare.net', 'Sokol', '2023-01-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (10, 'Nani Shakspeare', 'nshakspeare9@mlb.com', 'Ixopo', '2022-05-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (11, 'Elliot Hancke', 'ehanckea@photobucket.com', 'Неготино', '2022-08-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (12, 'Farlie Webermann', 'fwebermannb@howstuffworks.com', 'Boucherville', '2022-08-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (13, 'Blinny Scoyne', 'bscoynec@hp.com', 'Kuta', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (14, 'Randie Barreau', 'rbarreaud@pbs.org', 'Banjar Bengkelgede', '2022-07-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (15, null, 'vsmallwoode@arizona.edu', 'Mao’ershan', '2022-06-02');
insert into customers (customer_id, customer_name, email, city, signup_date) values (16, 'Giovanna Headly', 'gheadlyf@dagondesign.com', null, '2022-11-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (17, 'Esmaria Winsor', null, 'Krajan Dukuhseti', '2022-05-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (18, 'Georgianna Sculley', 'gsculleyh@europa.eu', null, '2022-09-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (19, 'Sally Flook', 'sflooki@hc360.com', 'Cipinang', '2023-01-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (20, 'Erv Bayston', 'ebaystonj@google.nl', 'Kendal', '2022-06-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (21, null, 'rlathomk@gov.uk', 'Esso', '2022-06-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (22, 'Kass Punchard', 'kpunchardl@cbc.ca', 'Pecatu', '2023-02-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (23, 'Luisa Lapre', 'llaprem@deliciousdays.com', 'Batudulang', '2022-08-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (24, 'Mae Fevier', 'mfeviern@moonfruit.com', 'Palmasola', '2022-05-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (25, 'Camila Glantz', 'cglantzo@ucoz.com', 'Fufang', '2022-08-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (26, 'Marketa Matterface', 'mmatterfacep@sohu.com', 'Anjirserapat', '2022-11-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (27, 'Becka Shrieves', 'bshrievesq@qq.com', 'Limoges', '2022-03-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (28, 'Juditha Cooke', 'jcooker@umn.edu', 'Hongtu', '2022-06-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (29, 'Margaret Ciccone', 'mciccones@booking.com', null, '2022-11-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (30, 'Alane Plume', 'aplumet@kickstarter.com', 'Marinha', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (31, 'Nataniel Lincey', 'nlinceyu@comcast.net', 'Luoxiong', '2022-05-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (32, 'Esteban Naldrett', 'enaldrettv@ameblo.jp', 'Santa Catalina Norte', '2022-10-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (33, 'Rand Van Brug', 'rvanw@google.nl', 'Preko', '2022-11-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (34, 'Jeremie Bearham', 'jbearhamx@discuz.net', null, '2022-10-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (35, 'Clyde Chape', 'cchapey@guardian.co.uk', 'Nempel', '2022-10-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (36, 'Viviene Assiratti', 'vassirattiz@naver.com', 'Nybro', '2022-12-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (37, 'Martita Goacher', 'mgoacher10@foxnews.com', 'Ballylinan', '2022-04-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (38, 'Stuart Breitler', 'sbreitler11@mit.edu', 'Tailing', '2022-05-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (39, 'Tim Rowledge', null, 'Matmata', '2023-01-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (40, 'Roseann Enoch', 'renoch13@engadget.com', 'Hejiaping', '2022-10-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (41, 'Helaine O''Dogherty', 'hodogherty14@squarespace.com', 'Beiling', '2022-08-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (42, 'Norby Shucksmith', 'nshucksmith15@storify.com', 'Formosa', '2023-02-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (43, 'Skyler Stichel', 'sstichel16@last.fm', 'Lloque', '2022-12-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (44, 'Liam Lesley', 'llesley17@histats.com', 'Leuwayang', '2022-11-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (45, 'Peggi Dunnico', 'pdunnico18@businessinsider.com', 'Tost', '2022-12-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (46, null, null, 'Pamakayo', '2022-07-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (47, 'Arden Antoniewicz', null, 'Piña', '2022-12-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (48, 'Giavani Lunbech', 'glunbech1b@people.com.cn', 'Preobrazheniye', '2022-10-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (49, 'Haskell Blackaby', 'hblackaby1c@zimbio.com', 'Dīvāndarreh', '2022-10-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (50, 'Rebekah Gask', 'rgask1d@etsy.com', null, '2022-07-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (51, null, null, 'Prince Albert', '2022-09-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (52, 'Myranda Trengove', 'mtrengove1f@wix.com', 'La Loma', '2022-08-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (53, 'Marcella Sinncock', 'msinncock1g@wiley.com', 'Lidingö', '2022-07-02');
insert into customers (customer_id, customer_name, email, city, signup_date) values (54, 'Olvan Weetch', 'oweetch1h@hubpages.com', 'Sa Kaeo', '2022-10-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (55, 'Augustine Lanahan', 'alanahan1i@t.co', 'Prinza', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (56, 'Hilton Courtese', 'hcourtese1j@hugedomains.com', 'Vol’no-Nadezhdinskoye', '2022-10-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (57, 'Maxwell Wooles', 'mwooles1k@senate.gov', 'Las Vegas', '2022-10-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (58, 'Aundrea Hambrook', 'ahambrook1l@yellowpages.com', 'Tozeur', '2022-09-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (59, 'Dolly Frew', 'dfrew1m@ed.gov', 'Stockholm', '2022-05-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (60, 'Hillel Cromb', 'hcromb1n@nasa.gov', 'Igarapé', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (61, 'Laetitia Dinzey', null, 'Waekolong', '2022-07-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (62, 'Hirsch Carnachen', 'hcarnachen1p@freewebs.com', 'Saint-Brieuc', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (63, 'Lyell Macia', 'lmacia1q@wordpress.org', 'Pengchang', '2022-04-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (64, 'Rodney Elverstone', 'relverstone1r@linkedin.com', null, '2022-03-31');
insert into customers (customer_id, customer_name, email, city, signup_date) values (65, null, null, 'Boršice', '2022-06-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (66, 'Emlynn Cultcheth', 'ecultcheth1t@comcast.net', 'Liucheng', '2022-11-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (67, 'Averell Knutton', 'aknutton1u@smugmug.com', 'São Mamede de Infesta', '2022-10-02');
insert into customers (customer_id, customer_name, email, city, signup_date) values (68, 'Bonnibelle Savaage', 'bsavaage1v@cmu.edu', 'Pigí', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (69, 'Salmon Llewelly', 'sllewelly1w@ox.ac.uk', 'Gampingan', '2022-04-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (70, 'Ula Kleanthous', 'ukleanthous1x@cisco.com', 'Zhalinghu', '2022-08-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (71, 'Lizzie Domone', null, 'Verkhniy Baskunchak', '2023-03-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (72, 'Shermie Bodle', 'sbodle1z@nytimes.com', 'Aţ Ţawīlah', '2022-03-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (73, 'Cyrillus Messenger', 'cmessenger20@fastcompany.com', 'Boneng', '2022-11-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (74, 'Angel Bramont', null, 'Tsurusaki', '2022-06-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (75, 'Thekla Cheesley', 'tcheesley22@usgs.gov', 'Kačanik', '2023-02-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (76, 'Murdock Abdey', 'mabdey23@desdev.cn', null, '2022-08-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (77, 'Dorian Bottomley', 'dbottomley24@java.com', 'Tianya', '2022-11-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (78, 'Arlina Daniau', 'adaniau25@pinterest.com', 'Kingsey Falls', '2022-12-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (79, 'Yorgo Bick', 'ybick26@dropbox.com', 'Khawrah', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (80, 'Morley Nand', null, 'Areado', '2022-06-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (81, 'Herbie Clapperton', 'hclapperton28@rakuten.co.jp', 'Spas’ke', '2022-10-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (82, 'Franchot Hartell', 'fhartell29@mtv.com', 'Aquiraz', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (83, 'Dorene Derges', 'dderges2a@ox.ac.uk', 'Kurovskoye', '2022-06-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (84, 'Nikolos Dolden', 'ndolden2b@cargocollective.com', 'La Ceja', '2023-03-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (85, 'Nataniel Purvess', 'npurvess2c@chicagotribune.com', 'Dahe', '2023-02-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (86, 'Nap Kershow', 'nkershow2d@360.cn', 'San Jerónimo', '2023-02-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (87, 'Velma Kenningham', 'vkenningham2e@dmoz.org', 'São José de Ribamar', '2022-05-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (88, 'Raye Escott', 'rescott2f@webs.com', 'Gnosjö', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (89, 'Kristy Ricks', 'kricks2g@blogtalkradio.com', 'Tsagaan-Owoo', '2022-05-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (90, 'Godart Van Vuuren', 'gvan2h@tuttocitta.it', null, '2023-01-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (91, 'Wanda Gabb', 'wgabb2i@cocolog-nifty.com', 'Vilnius', '2022-12-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (92, 'Wendie Huxter', null, 'Lushuihe', '2022-07-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (93, 'Minda Bush', 'mbush2k@usnews.com', null, '2022-04-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (94, 'Illa Beloe', 'ibeloe2l@about.com', 'Blobo', '2023-02-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (95, null, 'biddy2m@yale.edu', 'Nagorsk', '2023-02-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (96, 'Melinda Blindt', 'mblindt2n@army.mil', null, '2022-08-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (97, 'Lucita Sapauton', null, 'Guangshun', '2022-12-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (98, 'Smith Skillitt', 'sskillitt2p@is.gd', 'San Antonio', '2022-09-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (99, 'Vicki Darree', 'vdarree2q@flavors.me', 'Itaocara', '2023-02-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (100, 'Gisella Lynagh', 'glynagh2r@networksolutions.com', 'Saarbrücken', '2023-02-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (101, 'Mylo Swallwell', 'mswallwell2s@dell.com', 'Pinayagan Norte', '2023-01-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (102, 'Dorelia Hawthorne', null, 'Kalej', '2022-10-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (103, 'Yehudit Klimmek', 'yklimmek2u@e-recht24.de', 'Perstorp', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (104, 'Karol Mordaunt', 'kmordaunt2v@boston.com', 'Tertek', '2022-07-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (105, 'Nobe Ledson', 'nledson2w@thetimes.co.uk', 'Zagnitkiv', '2023-02-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (106, 'Gail Spinello', 'gspinello2x@samsung.com', 'Haradok', '2022-11-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (107, 'Esmeralda Hazle', 'ehazle2y@is.gd', 'Chornorudka', '2022-09-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (108, 'Peggi Culley', 'pculley2z@friendfeed.com', 'Serzedo', '2022-11-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (109, 'Oswald Bartelot', 'obartelot30@nyu.edu', 'Socota', '2023-01-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (110, 'Bevvy Scrowton', 'bscrowton31@g.co', 'Shicheng', '2022-07-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (111, 'Lemar Polycote', 'lpolycote32@independent.co.uk', 'Santa Cruz', '2022-12-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (112, 'Mauricio Maudett', 'mmaudett33@hubpages.com', null, '2022-12-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (113, 'Claybourne McVeagh', 'cmcveagh34@github.com', 'Rumelange', '2022-06-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (114, 'Hoyt Croix', null, 'Al Faḩāḩīl', '2022-08-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (115, 'Bartie Scamp', 'bscamp36@jalbum.net', 'Hasaki', '2023-02-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (116, 'Geralda Sagg', 'gsagg37@goo.ne.jp', 'Koceljeva', '2023-01-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (117, null, null, 'Shreveport', '2023-02-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (118, 'Candida Goalby', null, 'Zrenjanin', '2022-10-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (119, 'Faber Ribou', 'fribou3a@photobucket.com', 'Tolotangga', '2022-11-02');
insert into customers (customer_id, customer_name, email, city, signup_date) values (120, 'Matthiew Alywin', 'malywin3b@oakley.com', 'Dambarta', '2022-06-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (121, 'Linda Swadlen', 'lswadlen3c@youtube.com', 'Thị Trấn Mỹ Lộc', '2022-07-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (122, 'Iorgos Wigan', 'iwigan3d@foxnews.com', 'Abut', '2022-10-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (123, 'Edward Boyes', 'eboyes3e@rediff.com', 'Wendengying', '2022-04-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (124, 'Alys Willoway', 'awilloway3f@ow.ly', 'Cravinhos', '2022-06-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (125, 'Elihu Chelnam', 'echelnam3g@tamu.edu', 'Chowki Jamali', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (126, 'Trip McGroarty', null, null, '2022-08-31');
insert into customers (customer_id, customer_name, email, city, signup_date) values (127, 'North Philot', 'nphilot3i@usgs.gov', 'Cravo Norte', '2022-12-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (128, 'Anna Marmion', 'amarmion3j@apache.org', 'Hyesan-dong', '2022-12-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (129, 'Jesselyn Guidoni', 'jguidoni3k@naver.com', 'Peer', '2022-08-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (130, 'Griswold Barrim', 'gbarrim3l@ustream.tv', 'Daja', '2022-09-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (131, 'Kiel Lilie', 'klilie3m@columbia.edu', 'Qamdo', '2023-01-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (132, 'Shandeigh McConigal', 'smcconigal3n@ucoz.ru', 'Kayukembang', '2023-02-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (133, 'Shanie Armell', null, 'Kutapanjang', '2022-09-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (134, 'Ileana Worsnap', 'iworsnap3p@tamu.edu', 'Indralayang', '2022-12-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (135, 'Camey Reynard', 'creynard3q@soup.io', 'Doetinchem', '2022-09-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (136, 'Mic Aingel', 'maingel3r@disqus.com', 'Al Ḩāmūl', '2023-02-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (137, 'Lucais Gatehouse', 'lgatehouse3s@w3.org', 'Nūbā', '2022-12-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (138, 'Emerson Wood', 'ewood3t@cdbaby.com', 'Lubei', '2022-10-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (139, 'Pacorro Saberton', 'psaberton3u@unesco.org', 'Oliveirinha', '2022-10-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (140, 'Cori Hews', 'chews3v@usda.gov', 'Pepayan', '2022-06-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (141, null, 'bvaar3w@pbs.org', 'Cheongju-si', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (142, 'Roxane Neames', 'rneames3x@techcrunch.com', 'Manonjaya', '2022-08-02');
insert into customers (customer_id, customer_name, email, city, signup_date) values (143, 'Perry Blaszczak', 'pblaszczak3y@friendfeed.com', 'Aveleda', '2022-11-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (144, 'Petrina Bellam', 'pbellam3z@geocities.jp', 'Mirzāpur', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (145, 'Lucky Rosettini', 'lrosettini40@plala.or.jp', 'Crespo', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (146, 'Almeria Wesley', 'awesley41@utexas.edu', 'Yayao', '2023-02-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (147, 'Krystal Portch', 'kportch42@omniture.com', 'Lagoa Seca', '2022-06-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (148, 'Laure Napleton', 'lnapleton43@thetimes.co.uk', 'Skópelos', '2022-07-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (149, null, 'bantoniak44@earthlink.net', 'Gosen', '2022-11-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (150, 'Alvin Geharke', 'ageharke45@a8.net', 'Baní', '2022-11-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (151, null, 'bburwin46@google.ru', 'Fredrikstad', '2022-09-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (152, 'Sybila Knivett', 'sknivett47@naver.com', 'Carhuac', '2022-06-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (153, 'Harman Saltern', 'hsaltern48@nba.com', 'Maleevsk', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (154, 'Roldan Leverentz', 'rleverentz49@about.com', 'Neni', '2022-03-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (155, 'Cosmo Farragher', 'cfarragher4a@google.it', 'Martin', '2022-06-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (156, 'Thia Tickel', 'ttickel4b@ocn.ne.jp', 'Matiao', '2022-08-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (157, 'Gregoire Casini', 'gcasini4c@nhs.uk', 'Nanyuan', '2022-09-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (158, null, 'aogers4d@friendfeed.com', 'Richmond', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (159, 'Bernelle Arrol', 'barrol4e@seattletimes.com', 'Mişrātah', '2023-01-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (160, 'Alta Semken', 'asemken4f@vkontakte.ru', 'Arras', '2023-01-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (161, 'Aleen Shillinglaw', 'ashillinglaw4g@hc360.com', 'Kedungtulup', '2022-04-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (162, 'Xenos Handley', null, 'Diriomo', '2022-10-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (163, 'Curr Howerd', null, 'Sandviken', '2022-09-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (164, 'Uriel McGill', null, 'Kryevidh', '2022-11-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (165, 'Christine Brydell', 'cbrydell4k@gravatar.com', 'Gengqing', '2023-02-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (166, 'Ramonda Michell', 'rmichell4l@bluehost.com', 'Beppu', '2022-05-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (167, 'Binky Steele', 'bsteele4m@businessweek.com', 'Obršani', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (168, 'Ermengarde Ketteridge', 'eketteridge4n@earthlink.net', 'Zishan', '2022-07-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (169, 'Morna Gimbrett', 'mgimbrett4o@seattletimes.com', 'Qiaolin', '2023-01-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (170, 'Doretta Palliser', 'dpalliser4p@bravesites.com', 'Manlucahoc', '2022-04-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (171, 'Analiese Gillfillan', 'agillfillan4q@ted.com', 'Qingzhou', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (172, 'Chelsy Gowling', null, 'Claresholm', '2022-05-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (173, 'Sonnnie de Broke', null, 'Tripoli', '2022-06-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (174, 'Josie Latey', 'jlatey4t@netscape.com', 'Petäjävesi', '2022-05-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (175, 'Raddie Lesurf', 'rlesurf4u@chronoengine.com', 'Heshui', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (176, 'Helenelizabeth Yair', 'hyair4v@sitemeter.com', 'Tianyuan', '2022-12-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (177, 'Reena Avrahamov', 'ravrahamov4w@sciencedaily.com', 'Sepit', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (178, 'Max Wanklin', null, 'Xinchengzi', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (179, 'Cesar Aleksic', 'caleksic4y@example.com', 'Gongxi', '2023-02-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (180, 'Cord Djorevic', null, 'Cahuac', '2022-06-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (181, 'Dare Sobczak', 'dsobczak50@reddit.com', 'Catumbela', '2022-11-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (182, 'Carie Stronghill', 'cstronghill51@squidoo.com', 'Ibara', '2022-07-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (183, 'Daveta Tottman', 'dtottman52@bigcartel.com', 'Khotynets', '2022-07-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (184, null, 'hgreenland53@oracle.com', 'Litvínovice', '2022-04-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (185, 'Wilmette Shepherd', null, 'Añatuya', '2022-10-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (186, 'Butch Dilleway', 'bdilleway55@gizmodo.com', null, '2022-08-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (187, 'Dew Owens', 'dowens56@fda.gov', 'Łęczyce', '2023-01-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (188, 'Candi Papierz', null, 'Midland', '2022-06-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (189, 'Frank Bottoms', 'fbottoms58@msu.edu', 'Sainte-Sophie', '2022-04-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (190, 'Maye Jacmar', 'mjacmar59@homestead.com', 'Warwick', '2023-02-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (191, 'Kristina Tomczynski', 'ktomczynski5a@oakley.com', 'Jiangna', '2023-01-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (192, 'Asher Fromant', 'afromant5b@disqus.com', 'Brodarica', '2022-05-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (193, 'Franni Paler', 'fpaler5c@webeden.co.uk', 'Illela', '2023-01-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (194, 'Natty Vedstra', 'nvedstra5d@networksolutions.com', 'Sanom', '2023-02-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (195, 'Linoel Yggo', 'lyggo5e@reuters.com', 'Manzil Bū Zalafah', '2023-01-31');
insert into customers (customer_id, customer_name, email, city, signup_date) values (196, 'Aldwin Binning', 'abinning5f@ihg.com', 'Novokayakent', '2022-07-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (197, 'Cornelle Dinneges', 'cdinneges5g@linkedin.com', 'Baytā al Fawqā', '2022-08-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (198, 'Svend Fealey', 'sfealey5h@shop-pro.jp', 'Anahuac', '2022-12-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (199, 'Ashla Brunet', 'abrunet5i@miitbeian.gov.cn', 'Tassin-la-Demi-Lune', '2022-09-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (200, 'Ingeborg Woolaston', 'iwoolaston5j@gizmodo.com', 'Yambio', '2022-07-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (201, 'Tymothy O''Clery', 'toclery5k@amazon.co.jp', 'Eldoret', '2022-04-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (202, 'Giacomo Borland', 'gborland5l@theguardian.com', 'Jieting', '2022-09-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (203, 'Kipper Bierman', null, 'Noyal-sur-Vilaine', '2022-03-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (204, 'Martha Lundie', null, 'Yongchuan', '2023-01-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (205, 'Maegan Yitshak', null, 'Piotrków Trybunalski', '2022-10-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (206, 'Clarke MacCostye', 'cmaccostye5p@devhub.com', 'Atibaia', '2023-03-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (207, 'Odelle Bony', 'obony5q@virginia.edu', 'Kthella e Epërme', '2023-03-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (208, 'Catherina Kornes', null, 'Yuci', '2023-01-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (209, 'Maurine Endley', 'mendley5s@census.gov', 'Yirshi', '2022-07-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (210, 'Bobbette Pletts', 'bpletts5t@reddit.com', 'Huating', '2023-02-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (211, 'Kippie Stallibrass', 'kstallibrass5u@berkeley.edu', 'Kärdla', '2022-09-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (212, 'Cyril Brettelle', null, null, '2022-09-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (213, 'Mignonne Poulett', 'mpoulett5w@sakura.ne.jp', 'Gubskaya', '2022-07-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (214, 'Deedee Tester', 'dtester5x@purevolume.com', 'Cela', '2023-02-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (215, 'Keelby Scaddon', 'kscaddon5y@cam.ac.uk', 'Lodoyo', '2022-09-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (216, 'Beryl Reddel', 'breddel5z@studiopress.com', null, '2022-07-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (217, 'Tye Fannon', 'tfannon60@discovery.com', 'Urus-Martan', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (218, 'Angela Murcutt', null, 'Kowo', '2023-02-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (219, 'Newton Jowsey', 'njowsey62@sfgate.com', 'Minggang', '2023-01-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (220, 'Elyn Forrington', 'eforrington63@indiegogo.com', 'Raša', '2022-05-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (221, 'Velvet Tattersill', 'vtattersill64@ocn.ne.jp', 'Kutamangu', '2022-05-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (222, 'Bernadette Hambrook', 'bhambrook65@deviantart.com', 'Stykkishólmur', '2023-01-31');
insert into customers (customer_id, customer_name, email, city, signup_date) values (223, 'Tristan Ennew', 'tennew66@skype.com', 'Taipinghu', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (224, 'William Piddlehinton', 'wpiddlehinton67@tuttocitta.it', 'Cotabambas', '2022-07-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (225, 'Deirdre Sheivels', 'dsheivels68@skyrock.com', 'Kultayevo', '2022-09-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (226, 'Piotr Espine', 'pespine69@harvard.edu', 'El Benque', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (227, 'Minetta Dumbarton', 'mdumbarton6a@telegraph.co.uk', 'Teseney', '2022-05-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (228, 'Hayley Ivanishev', 'hivanishev6b@seattletimes.com', 'San José', '2022-07-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (229, 'Leonid Gummoe', 'lgummoe6c@chicagotribune.com', 'Vanadzor', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (230, 'Benedikta Covendon', 'bcovendon6d@whitehouse.gov', 'Sindangsari', '2022-12-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (231, 'Jdavie Loadsman', 'jloadsman6e@acquirethisname.com', 'Makanya', '2022-08-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (232, 'Elia Frammingham', 'eframmingham6f@wordpress.com', 'Panadura', '2022-04-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (233, 'Karalee Fielden', 'kfielden6g@edublogs.org', 'Kemijärvi', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (234, 'Randee Cicchitello', 'rcicchitello6h@storify.com', 'Lingkou', '2022-05-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (235, 'Merilyn Bravery', null, 'Quimbaya', '2022-05-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (236, 'Patrick Howler', 'phowler6j@furl.net', 'Donetsk', '2022-11-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (237, 'Zeb Beven', 'zbeven6k@mysql.com', 'Guéret', '2023-02-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (238, 'Curcio Bryce', 'cbryce6l@dropbox.com', 'Kozyatyn', '2022-11-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (239, 'Terry Videneev', 'tvideneev6m@taobao.com', 'Cové', '2022-08-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (240, null, 'lmeiningen6n@baidu.com', 'Chongru', '2023-03-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (241, 'Gabrila Lewsie', null, 'Göteborg', '2022-04-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (242, 'Tricia Barbisch', null, 'Kandava', '2022-12-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (243, 'Nissy McLeod', 'nmcleod6q@netvibes.com', 'Hal’shany', '2022-09-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (244, 'Haze Ditchett', null, 'Quận Tân Phú', '2022-05-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (245, 'Skyler Munday', null, 'Torre', '2022-05-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (246, 'Arlinda Strangwood', 'astrangwood6t@homestead.com', 'Nevel’', '2022-08-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (247, null, 'slazer6u@sun.com', 'Leiden', '2022-10-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (248, 'Laraine Timlin', 'ltimlin6v@newyorker.com', 'Puan Selatan', '2022-10-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (249, 'Zelda Renol', 'zrenol6w@edublogs.org', 'Usu', '2022-12-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (250, 'Jonell Kiddye', 'jkiddye6x@google.cn', 'Tsalgar', '2022-07-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (251, 'Ilsa Saffe', 'isaffe6y@odnoklassniki.ru', 'Sukorejo', '2022-08-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (252, 'Corrinne Ricardo', 'cricardo6z@unc.edu', 'Pederneiras', '2022-07-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (253, 'Delmore Bowne', 'dbowne70@nifty.com', 'Guay', '2022-06-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (254, 'Robin Spillman', 'rspillman71@wikia.com', 'Pysznica', '2022-07-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (255, null, 'arepp72@ed.gov', 'Piedecuesta', '2023-01-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (256, 'Roosevelt Colvine', 'rcolvine73@naver.com', 'Poli', '2022-11-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (257, 'Van Phillcock', 'vphillcock74@devhub.com', 'Al Ḩāḑir', '2023-03-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (258, 'Amil Muzzi', 'amuzzi75@wikipedia.org', 'Ladhewāla Warāich', '2022-12-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (259, 'Alvira Addyman', null, 'Sukhirin', '2022-11-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (260, 'Leslie Parnaby', 'lparnaby77@meetup.com', 'Hor', '2023-02-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (261, 'Gayle Bosson', null, 'Amagi', '2023-01-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (262, 'Margy Kiwitz', 'mkiwitz79@soup.io', 'Miaoshou', '2022-07-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (263, 'Ines Boxhill', 'iboxhill7a@spotify.com', 'Kybartai', '2022-05-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (264, 'Eba Hambers', 'ehambers7b@ycombinator.com', 'Kuzhu', '2022-05-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (265, 'Sheree Gartsyde', 'sgartsyde7c@stanford.edu', 'Krajan Kedungsalam', '2022-09-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (266, 'Dilly Platt', 'dplatt7d@wikimedia.org', 'Outeiro', '2022-04-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (267, 'Marleen Twatt', 'mtwatt7e@mapy.cz', 'Urus-Martan', '2022-12-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (268, 'Jan Graveney', 'jgraveney7f@sciencedirect.com', 'Shicheng', '2022-11-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (269, null, 'agambie7g@nytimes.com', 'Vila Boa do Bispo', '2022-09-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (270, 'Zedekiah Stapells', 'zstapells7h@psu.edu', 'San Pedro', '2022-12-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (271, 'Hanson Reany', 'hreany7i@nps.gov', 'Yiqi', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (272, 'Claudian Overshott', null, 'Kurnia', '2022-09-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (273, 'Marlowe Kingett', 'mkingett7k@stanford.edu', 'Tambaú', '2022-07-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (274, 'Denys Ramsted', 'dramsted7l@weibo.com', 'Katoro', '2023-03-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (275, 'Irvine Doherty', 'idoherty7m@cnn.com', 'Conchagua', '2022-05-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (276, 'Angela Lefort', 'alefort7n@princeton.edu', 'Pendiqing', '2022-05-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (277, 'Cassi Merrill', null, 'Baleal', '2023-01-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (278, null, null, 'Góra', '2022-09-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (279, 'Vivia Eversley', null, 'Guariba', '2022-05-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (280, 'Saunders Wibberley', 'swibberley7r@t-online.de', 'Xipu', '2022-12-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (281, 'Gerrard Everiss', null, 'Jandir', '2022-09-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (282, 'Kenon MacRonald', 'kmacronald7t@usa.gov', 'Badung', '2023-03-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (283, 'Merl Peron', 'mperon7u@weather.com', 'Malindi', '2022-12-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (284, null, 'akenson7v@opensource.org', 'Frederiksberg', '2023-02-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (285, 'Ciro Dyott', 'cdyott7w@lycos.com', 'Medellín', '2022-12-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (286, 'Joli Casaccia', 'jcasaccia7x@flickr.com', 'Bukomansimbi', '2022-12-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (287, 'Collin Eggleson', 'ceggleson7y@sourceforge.net', 'Bayan Hot', '2022-07-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (288, 'Ammamaria Bellis', 'abellis7z@mlb.com', 'Halat', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (289, 'Melita Wyrill', 'mwyrill80@marketwatch.com', 'Lianzhu', '2022-12-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (290, 'Torr Kane', 'tkane81@unesco.org', 'Wang Yang', '2022-09-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (291, 'Kalindi Skellorne', 'kskellorne82@arstechnica.com', 'Obita', '2022-04-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (292, 'Cornall Disman', 'cdisman83@amazon.co.uk', 'Tamot', '2022-12-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (293, 'Bengt Leneham', 'bleneham84@weather.com', 'Saint-Chamond', '2022-08-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (294, 'Carolus Haseman', 'chaseman85@jimdo.com', 'Aourir', '2023-02-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (295, 'Flin MacGaughie', 'fmacgaughie86@scientificamerican.com', 'Cuenca', '2022-06-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (296, 'Eddi Baptist', null, 'Molina', '2023-01-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (297, 'Quintus Mattioni', 'qmattioni88@meetup.com', 'Hefu', '2022-11-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (298, 'Norby MacRinn', 'nmacrinn89@tripod.com', 'Dijon', '2023-01-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (299, 'Natalya Richin', null, 'Bakung', '2022-04-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (300, 'Vonni Brownsey', 'vbrownsey8b@soup.io', 'Cielmice', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (301, 'Derril Chanders', 'dchanders8c@gov.uk', 'Bualan', '2022-11-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (302, 'Maurine Van Leeuwen', null, 'Mirecourt', '2023-01-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (303, 'Katharine Hunnaball', 'khunnaball8e@accuweather.com', 'Nevers', '2022-07-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (304, 'Kippie Bratt', 'kbratt8f@cnbc.com', 'Sułoszowa', '2022-08-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (305, null, 'alande8g@dmoz.org', 'Guaratinguetá', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (306, 'Clementine Mustard', 'cmustard8h@photobucket.com', 'Setúbal', '2023-02-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (307, 'Mariel Tofano', 'mtofano8i@php.net', 'Velizh', '2022-10-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (308, 'Wrennie Buye', null, 'Shuyuan Zhen', '2022-11-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (309, 'Kalinda Newns', 'knewns8k@arstechnica.com', 'Chachagüí', '2022-06-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (310, 'Lucila Raulstone', 'lraulstone8l@aol.com', 'Jeseník', '2022-07-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (311, 'Jacky Bigrigg', 'jbigrigg8m@engadget.com', 'Vinež', '2022-06-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (312, 'Tuckie Pappi', 'tpappi8n@slideshare.net', 'Seremban', '2022-09-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (313, 'Ari Stanfield', 'astanfield8o@amazon.co.jp', 'Triandría', '2022-12-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (314, 'Isidro Carman', 'icarman8p@hhs.gov', 'Zhangjiawan', '2023-01-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (315, 'Corette South', 'csouth8q@homestead.com', 'Yantianhe', '2023-02-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (316, 'Stearn Dellenbrok', null, 'Matamey', '2022-11-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (317, 'Bert Cherry', 'bcherry8s@google.cn', null, '2022-03-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (318, 'Ethe Midgely', 'emidgely8t@nymag.com', 'Siumate', '2023-02-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (319, 'Tanney Thyer', 'tthyer8u@eventbrite.com', 'Khorugh', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (320, 'Vonny Mattinson', 'vmattinson8v@google.com.au', 'Jovellanos', '2022-05-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (321, 'Arny Lowth', 'alowth8w@imdb.com', 'Sendang', '2023-01-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (322, 'Hillary Cattonnet', 'hcattonnet8x@de.vu', 'Batur Kidul', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (323, 'Elnore Thacke', 'ethacke8y@xinhuanet.com', 'Kitchener', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (324, 'Brodie Teas', 'bteas8z@51.la', 'Piotrków Trybunalski', '2023-03-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (325, null, 'darstall90@bloglines.com', 'Uglyanets', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (326, 'Christophorus Sleet', null, 'Rumyantsevo', '2022-04-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (327, 'Doria Millhill', 'dmillhill92@surveymonkey.com', 'Mamonit', '2023-02-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (328, 'Leonie Gouthier', 'lgouthier93@ucoz.com', 'Dalang', '2022-05-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (329, 'Stuart Randall', 'srandall94@salon.com', 'São Pedro de Trafaria', '2022-08-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (330, 'Mackenzie Minshall', 'mminshall95@1688.com', 'Parthenay', '2023-02-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (331, 'Beatrix Chaman', 'bchaman96@apple.com', null, '2022-11-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (332, 'Cecilia Esgate', 'cesgate97@geocities.com', 'Tuhe', '2022-06-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (333, 'Mort MacCroary', null, 'Seltjarnarnes', '2022-07-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (334, 'Demeter Kochel', 'dkochel99@state.gov', 'Yermish’', '2022-04-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (335, 'Edin Blacker', 'eblacker9a@wordpress.com', 'Rybnoye', '2022-03-31');
insert into customers (customer_id, customer_name, email, city, signup_date) values (336, 'Lona Stonier', 'lstonier9b@scientificamerican.com', 'Sokal’', '2022-05-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (337, 'Cornell Byforth', 'cbyforth9c@taobao.com', 'Kil', '2022-07-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (338, null, 'rscane9d@dmoz.org', null, '2023-03-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (339, 'Norma Oman', 'noman9e@sohu.com', 'Staryy Oskol', '2022-08-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (340, 'Dyan Carlett', 'dcarlett9f@reverbnation.com', 'Budënnovsk', '2022-07-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (341, 'Jania Landall', 'jlandall9g@fema.gov', 'Sivaki', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (342, 'Winn Balog', 'wbalog9h@moonfruit.com', 'Leuburi', '2023-01-31');
insert into customers (customer_id, customer_name, email, city, signup_date) values (343, 'Filberte Venditti', null, 'Talisay', '2022-10-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (344, 'Fayina Filler', 'ffiller9j@tamu.edu', 'Az Zulfi', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (345, 'Wash Siemens', 'wsiemens9k@vk.com', 'Dahu', '2022-09-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (346, 'Koenraad Radcliffe', 'kradcliffe9l@mashable.com', 'Okiot', '2023-02-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (347, 'Tiphanie Nolda', 'tnolda9m@webnode.com', 'Zapolyarnyy', '2022-03-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (348, 'Dorena Fochs', 'dfochs9n@people.com.cn', 'Cubará', '2022-07-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (349, 'Lion Burrage', 'lburrage9o@flavors.me', 'Pandangan Kulon', '2022-09-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (350, 'Filia McEniry', 'fmceniry9p@bbc.co.uk', 'Bongandanga', '2022-07-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (351, 'Taryn Fronczak', 'tfronczak9q@yelp.com', 'Bilalang', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (352, 'Pascale Munkley', 'pmunkley9r@ca.gov', 'Papër', '2022-03-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (353, 'Drew McKernan', 'dmckernan9s@taobao.com', 'Kout na Šumavě', '2023-02-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (354, 'Spencer Robbins', null, 'Kanda', '2023-01-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (355, 'Cora Cohalan', null, 'Vinha', '2023-03-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (356, 'Genny Cowperthwaite', 'gcowperthwaite9v@yandex.ru', 'Bakadagy', '2022-07-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (357, 'Augustine Posselow', 'aposselow9w@google.fr', 'Huangbei', '2022-11-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (358, 'Suzanna Birdwhistell', 'sbirdwhistell9x@weather.com', 'Wangyi Zhendian', '2022-09-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (359, 'Druci Titt', null, 'Kasukabe', '2022-12-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (360, null, 'togormally9z@tiny.cc', 'Xitianwei', '2022-12-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (361, 'Emlynne Thames', 'ethamesa0@mozilla.com', 'San Pedro', '2022-06-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (362, 'Madelena Logsdail', 'mlogsdaila1@uol.com.br', 'Dārayyā', '2022-11-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (363, 'Brander Monteath', null, 'Xiaojinkou', '2022-05-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (364, 'Melonie Pottle', 'mpottlea3@nifty.com', 'Osa', '2022-04-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (365, 'Dame Denley', 'ddenleya4@engadget.com', null, '2022-10-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (366, 'Bail Peters', null, 'Öndörhoshuu', '2022-08-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (367, 'Erick MacGow', 'emacgowa6@plala.or.jp', null, '2022-12-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (368, 'Consalve Hedden', 'cheddena7@theatlantic.com', 'Bessonovka', '2022-09-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (369, 'Joscelin McCloughlin', 'jmccloughlina8@columbia.edu', 'Napu', '2022-04-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (370, 'Davy Fey', 'dfeya9@ox.ac.uk', 'Арачиново', '2022-07-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (371, 'Nahum Saleway', 'nsalewayaa@nifty.com', 'Strasbourg', '2022-11-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (372, 'Ivy Hepher', 'ihepherab@princeton.edu', 'Fonte de Angeão', '2022-05-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (373, 'Sheryl Kieran', 'skieranac@google.com', 'Rosthern', '2022-08-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (374, 'Nevile Brookwell', 'nbrookwellad@epa.gov', 'Pangguang', '2023-02-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (375, 'Charlena Barnhill', 'cbarnhillae@technorati.com', 'Bududa', '2022-11-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (376, 'Ives Bourgourd', null, 'Krasnokamsk', '2022-09-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (377, 'Isidro Northing', 'inorthingag@harvard.edu', 'Dragash', '2022-05-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (378, 'Nye Colwill', 'ncolwillah@skype.com', 'Armentières', '2022-09-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (379, 'Marylee Gorry', 'mgorryai@amazon.co.uk', 'Glushkovo', '2022-11-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (380, 'Renae Herion', 'rherionaj@sakura.ne.jp', 'Argungu', '2022-06-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (381, 'Jerri Mariel', 'jmarielak@free.fr', 'Sihai', '2022-08-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (382, 'Brana Brokenshaw', 'bbrokenshawal@artisteer.com', 'Liangjing', '2022-05-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (383, 'Nigel Edgler', 'nedgleram@reference.com', null, '2022-11-02');
insert into customers (customer_id, customer_name, email, city, signup_date) values (384, null, null, 'Kolirerek', '2023-01-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (385, 'Ola Nurden', 'onurdenao@columbia.edu', 'Pantukan', '2023-03-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (386, 'Selby Stapylton', 'sstapyltonap@cafepress.com', 'Obo', '2022-06-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (387, 'Fremont Moran', 'fmoranaq@wikia.com', 'Khvānsār', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (388, 'Briggs Killingworth', 'bkillingworthar@paginegialle.it', 'Liuduzhai', '2022-05-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (389, 'Rog Urrey', 'rurreyas@cnet.com', null, '2022-12-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (390, 'Judy Cultcheth', 'jcultchethat@sfgate.com', 'Beixin', '2023-01-31');
insert into customers (customer_id, customer_name, email, city, signup_date) values (391, 'Nealy Davids', 'ndavidsau@addthis.com', null, '2022-07-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (392, null, 'ddedeiav@wiley.com', null, '2022-09-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (393, 'Aron O''Brogane', 'aobroganeaw@java.com', 'Qŭshkŭpir', '2022-11-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (394, 'Rheta Cullrford', 'rcullrfordax@biblegateway.com', 'Granja do Tedo', '2022-07-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (395, 'Francyne Stratz', 'fstratzay@chronoengine.com', 'Pulap', '2022-09-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (396, 'Nollie Liggett', null, 'Gornji Petrovci', '2022-12-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (397, 'Thalia Quickenden', null, 'Semikarakorsk', '2022-10-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (398, 'Paige Lansdown', 'plansdownb1@cisco.com', 'Lafiagi', '2022-06-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (399, 'Maryrose Tuffield', 'mtuffieldb2@wikia.com', 'Tanjung', '2022-10-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (400, 'Ethelind Farnorth', 'efarnorthb3@list-manage.com', 'Taphan Hin', '2022-07-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (401, null, 'gduffusb4@privacy.gov.au', 'Las Matas de Santa Cruz', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (402, 'Camila Van der Hoven', 'cvanb5@army.mil', 'Cimongkor', '2022-04-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (403, null, 'sartinstallb6@google.com', 'Gyangkar', '2022-03-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (404, null, 'sjohanchonb7@sourceforge.net', 'Balongmulyo', '2023-01-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (405, 'Michaelina Gilbey', null, 'Marquard', '2022-08-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (406, 'Olenka Dumbrell', 'odumbrellb9@toplist.cz', 'Lebedyn', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (407, null, 'avasilovba@yale.edu', 'La Romana', '2023-02-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (408, 'Kinna Fawdry', 'kfawdrybb@bluehost.com', 'Zhaoyuan', '2022-08-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (409, 'Inglis Wardrop', null, 'Shenwan', '2023-03-03');
insert into customers (customer_id, customer_name, email, city, signup_date) values (410, 'Madalyn Wimpeney', 'mwimpeneybd@issuu.com', 'Fonteleite', '2022-04-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (411, null, 'alowerbe@scientificamerican.com', 'Qarshi', '2022-10-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (412, 'Cirstoforo Creenan', 'ccreenanbf@aol.com', 'Saraburi', '2023-01-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (413, 'Petrina Sarll', 'psarllbg@patch.com', 'Hunkuyi', '2022-05-13');
insert into customers (customer_id, customer_name, email, city, signup_date) values (414, 'Chryste Ivancevic', 'civancevicbh@cafepress.com', 'Hernani', '2022-07-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (415, 'Merla Oxtoby', 'moxtobybi@wufoo.com', null, '2022-11-04');
insert into customers (customer_id, customer_name, email, city, signup_date) values (416, null, 'jphilimorebj@yahoo.co.jp', 'Phlapphla Chai', '2022-04-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (417, 'Zacharia Cavan', 'zcavanbk@rambler.ru', 'Kaytitinga', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (418, 'Finlay Ducarne', 'fducarnebl@instagram.com', 'Grajaú', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (419, 'Kordula Troppmann', 'ktroppmannbm@gov.uk', 'Charyshskoye', '2022-10-02');
insert into customers (customer_id, customer_name, email, city, signup_date) values (420, 'Beverley Hakey', 'bhakeybn@over-blog.com', 'Gereneng', '2022-07-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (421, 'Otha Cuddehay', 'ocuddehaybo@va.gov', 'Oslo', '2022-04-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (422, 'Vanny Chippin', 'vchippinbp@gnu.org', 'Anyuan', '2022-11-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (423, 'Annissa Capron', 'acapronbq@behance.net', 'Doong', '2023-01-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (424, 'Noe Bartelet', 'nbarteletbr@apple.com', 'Mossel Bay', '2022-07-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (425, 'Christian Chadbourne', 'cchadbournebs@phpbb.com', 'Goúvai', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (426, 'Yulma Frascone', 'yfrasconebt@163.com', 'Villasis', '2022-09-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (427, 'Annice Semorad', 'asemoradbu@meetup.com', 'Yuquan', '2022-11-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (428, null, 'mkiffbv@marriott.com', 'Cabrero', '2022-09-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (429, 'Drugi Boshell', 'dboshellbw@harvard.edu', 'Beppu', '2022-09-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (430, 'De Whitechurch', 'dwhitechurchbx@europa.eu', 'Kipushi', '2022-06-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (431, 'Waneta Pletts', 'wplettsby@ycombinator.com', 'Khon Buri', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (432, 'Penrod Howgego', 'phowgegobz@webeden.co.uk', 'Lat Lum Kaeo', '2022-11-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (433, 'Hamnet Turfes', null, 'Kawambwa', '2022-10-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (434, 'Emmi Lawlee', 'elawleec1@dagondesign.com', 'Hedong', '2022-03-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (435, 'Remington Byers', null, null, '2023-01-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (436, 'Shane Stubbings', 'sstubbingsc3@g.co', 'Santa Rosa', '2022-03-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (437, 'Ches Fenney', 'cfenneyc4@wiley.com', 'Phúc Yên', '2022-04-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (438, 'Georgeanna Cobbald', 'gcobbaldc5@usa.gov', 'Papilawe', '2023-01-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (439, 'Raynard Chucks', null, 'Muaralembu', '2022-09-14');
insert into customers (customer_id, customer_name, email, city, signup_date) values (440, 'Sax Pays', 'spaysc7@walmart.com', 'Bronnitsy', '2022-10-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (441, 'Gil Gethen', 'ggethenc8@about.com', 'Werangere', '2022-10-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (442, 'Julia Kittredge', 'jkittredgec9@buzzfeed.com', 'Zhitan', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (443, 'Cyrille Pretious', 'cpretiousca@oracle.com', 'Petaling Jaya', '2022-12-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (444, 'Rosina Maccree', 'rmaccreecb@amazon.co.uk', 'Runsonglaozhai', '2022-04-16');
insert into customers (customer_id, customer_name, email, city, signup_date) values (445, null, 'dprichardcc@gravatar.com', 'Tsiombe', '2022-05-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (446, 'Henrie Ambrosetti', 'hambrosetticd@dyndns.org', 'Gulrip’shi', '2022-08-31');
insert into customers (customer_id, customer_name, email, city, signup_date) values (447, 'Manuel Wyley', 'mwyleyce@accuweather.com', 'Nakło nad Notecią', '2023-02-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (448, 'Michaela Norssister', null, 'Washington', '2022-06-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (449, 'Clim Werendell', 'cwerendellcg@photobucket.com', 'Song', '2022-08-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (450, 'Reggis Click', null, 'Hāsilpur', '2022-03-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (451, 'Tulley Postles', 'tpostlesci@gnu.org', 'Alindao', '2022-08-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (452, 'Elisabet Gwynn', null, 'Zhitang', '2023-03-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (453, 'Rolph Seer', 'rseerck@ocn.ne.jp', 'Le Puy-en-Velay', '2022-11-02');
insert into customers (customer_id, customer_name, email, city, signup_date) values (454, 'Helena Cordobes', null, null, '2022-09-17');
insert into customers (customer_id, customer_name, email, city, signup_date) values (455, 'Tricia Feary', 'tfearycm@ocn.ne.jp', 'Wolowona', '2022-06-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (456, null, 'jkingescotcn@sitemeter.com', 'Yazd', '2022-06-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (457, 'Jarvis Maciejewski', null, 'Nossebro', '2023-01-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (458, 'Jeromy Dever', 'jdevercp@uol.com.br', 'Junglinster', '2022-11-29');
insert into customers (customer_id, customer_name, email, city, signup_date) values (459, 'Ediva Halleybone', null, 'Ifanadiana', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (460, 'Nessi Di Gregorio', 'ndicr@cloudflare.com', 'Douane', '2022-12-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (461, 'Gerik Stolze', null, 'Alimono', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (462, 'Engracia MacLise', 'emaclisect@auda.org.au', 'Serzedelo', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (463, 'Odille Timbs', 'otimbscu@yahoo.com', 'Nowe Miasto nad Pilicą', '2022-08-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (464, 'Gunar Martensen', null, 'Velestíno', '2022-11-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (465, 'Layton Georgius', 'lgeorgiuscw@ucsd.edu', 'Fengle', '2022-08-25');
insert into customers (customer_id, customer_name, email, city, signup_date) values (466, 'Pascal Corkan', 'pcorkancx@slashdot.org', null, '2023-01-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (467, 'Barnard Champ', null, 'Kalunan', '2022-06-24');
insert into customers (customer_id, customer_name, email, city, signup_date) values (468, 'Theadora Sabati', 'tsabaticz@phpbb.com', 'San Diego', '2023-03-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (469, 'Vinni Windus', 'vwindusd0@1und1.de', 'Daping', '2022-08-28');
insert into customers (customer_id, customer_name, email, city, signup_date) values (470, 'Jennee Snodden', 'jsnoddend1@mail.ru', 'Trbovlje', '2022-11-20');
insert into customers (customer_id, customer_name, email, city, signup_date) values (471, 'Gerardo Stickney', 'gstickneyd2@si.edu', 'Saronída', '2022-06-19');
insert into customers (customer_id, customer_name, email, city, signup_date) values (472, 'Petrina MacKill', 'pmackilld3@mediafire.com', null, '2023-01-27');
insert into customers (customer_id, customer_name, email, city, signup_date) values (473, 'Gertruda Assiter', 'gassiterd4@soup.io', 'Lanhe', '2022-07-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (474, 'Ardeen Morter', 'amorterd5@yahoo.co.jp', 'Dordrecht', '2022-08-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (475, 'Pansie Gernier', 'pgernierd6@columbia.edu', 'Capão da Canoa', '2023-01-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (476, 'Fanny Brumbye', null, 'Jiaocun', '2023-01-10');
insert into customers (customer_id, customer_name, email, city, signup_date) values (477, null, 'mkeileyd8@scribd.com', 'Bintang', '2023-02-21');
insert into customers (customer_id, customer_name, email, city, signup_date) values (478, null, 'sdiwelld9@spotify.com', 'Qiaoyi', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (479, 'Amalita Hackinge', 'ahackingeda@soup.io', null, '2022-11-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (480, 'Farleigh Lilywhite', null, 'Glugur Tengah', '2023-01-08');
insert into customers (customer_id, customer_name, email, city, signup_date) values (481, 'Rocky Andrejevic', 'randrejevicdc@technorati.com', 'Qingshuihe', '2022-04-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (482, 'Georgine Jenny', null, 'Guarabira', '2023-02-06');
insert into customers (customer_id, customer_name, email, city, signup_date) values (483, 'Debi Robinette', 'drobinettede@friendfeed.com', 'Cisagu', '2022-07-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (484, 'Jourdan Leveret', 'jleveretdf@engadget.com', 'Pohrebyshche', '2022-12-15');
insert into customers (customer_id, customer_name, email, city, signup_date) values (485, 'Hester Slowey', 'hsloweydg@google.nl', 'Rameshki', '2023-03-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (486, 'Ardella Donnachie', 'adonnachiedh@alexa.com', 'Xinfeng', '2023-01-12');
insert into customers (customer_id, customer_name, email, city, signup_date) values (487, 'Aksel Romayn', null, 'Gjegjan', null);
insert into customers (customer_id, customer_name, email, city, signup_date) values (488, 'Darline Boatwright', null, 'Abovyan', '2023-03-11');
insert into customers (customer_id, customer_name, email, city, signup_date) values (489, 'Willy Grigorian', 'wgrigoriandk@unblog.fr', 'Jazovo', '2022-04-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (490, 'Kat Snelman', 'ksnelmandl@sciencedirect.com', 'Citeureup', '2022-03-18');
insert into customers (customer_id, customer_name, email, city, signup_date) values (491, 'Hagan Caughtry', null, 'Enrekang', '2022-10-26');
insert into customers (customer_id, customer_name, email, city, signup_date) values (492, 'Vinny Janik', 'vjanikdn@engadget.com', 'Biaoshan', '2022-10-30');
insert into customers (customer_id, customer_name, email, city, signup_date) values (493, 'Farris Stearn', null, 'Simunul', '2022-10-23');
insert into customers (customer_id, customer_name, email, city, signup_date) values (494, 'Fidelia Gartside', null, null, '2022-05-31');
insert into customers (customer_id, customer_name, email, city, signup_date) values (495, 'Bennett Dudin', 'bdudindq@ucoz.ru', 'La Victoria', '2022-04-09');
insert into customers (customer_id, customer_name, email, city, signup_date) values (496, 'Lenci Rzehor', 'lrzehordr@mashable.com', 'Lyakhovtsy', '2023-02-22');
insert into customers (customer_id, customer_name, email, city, signup_date) values (497, 'Hyman Desantis', 'hdesantisds@dedecms.com', 'Aras-asan', '2022-07-07');
insert into customers (customer_id, customer_name, email, city, signup_date) values (498, null, 'nsmithsondt@vinaora.com', 'Carleton-sur-Mer', '2023-01-05');
insert into customers (customer_id, customer_name, email, city, signup_date) values (499, 'Perrine Abrashkin', 'pabrashkindu@bbc.co.uk', 'San Juan', '2022-12-01');
insert into customers (customer_id, customer_name, email, city, signup_date) values (500, null, 'snavandv@forbes.com', 'Nekrasovka', '2023-01-13');
