insert into product (product_id, product_name, category, price) values (1, 'Italian Pasta', 'Food - Grains', 2.29);
insert into product (product_id, product_name, category, price) values (2, 'Electric Can Opener', 'Kitchen', 29.99);
insert into product (product_id, product_name, category, price) values (3, 'Emergency Preparedness Kit', 'Safety', 99.99);
insert into product (product_id, product_name, category, price) values (4, 'Lentil Soup (canned)', 'Food - Canned Goods', 1.99);
insert into product (product_id, product_name, category, price) values (5, null, 'Accessories', 29.99);
insert into product (product_id, product_name, category, price) values (6, 'High-Waisted Skirt', 'Clothing - Bottoms', 34.99);
insert into product (product_id, product_name, category, price) values (7, 'Ice Cream Scoop', 'Kitchen', 12.99);
insert into product (product_id, product_name, category, price) values (8, 'Frozen Mixed Vegetables', 'Food - Frozen', 1.99);
insert into product (product_id, product_name, category, price) values (9, 'Electric Skillet', 'Kitchen', 49.99);
insert into product (product_id, product_name, category, price) values (10, 'Freestanding Wine Rack', null, 79.99);
insert into product (product_id, product_name, category, price) values (11, 'Bluetooth Headphones', 'Audio', 79.99);
insert into product (product_id, product_name, category, price) values (12, 'Laptop Backpack', 'Accessories', 69.99);
insert into product (product_id, product_name, category, price) values (13, 'Kale & Quinoa Salad Mix', 'Food - Salads', 4.49);
insert into product (product_id, product_name, category, price) values (14, 'Black Bean & Corn Salad', 'Food - Salads', 3.99);
insert into product (product_id, product_name, category, price) values (15, 'Gardening Tools Set', 'Garden', 45);
insert into product (product_id, product_name, category, price) values (16, 'Weighted Jump Rope with Counter', 'Fitness', 14.99);
insert into product (product_id, product_name, category, price) values (17, 'Butternut Squash Soup', 'Food - Soups', 3.49);
insert into product (product_id, product_name, category, price) values (18, 'Wi-Fi Enabled Smart Light Switch', 'Smart Home', 24.99);
insert into product (product_id, product_name, category, price) values (19, 'Smartphone Camera Lens Kit', 'Photography', 19.99);
insert into product (product_id, product_name, category, price) values (20, 'Noise Reduction Headphones', 'Audio', 39.99);
